=== rpf1980/Desarrollo-Web/Ejercicios tipo examen XML DTD, CSS y XSLT/examen-01-proyecto/alumnos/e1-atributos.dtd
<!ELEMENT proyecto (datos_proyecto, dedicatoria, apartado+)>
<!ELEMENT datos_proyecto (titulo, autor+)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT dedicatoria (parrafo+)>
<!ELEMENT parrafo (#PCDATA)>
<!ELEMENT apartado (titulo, seccion*)>
<!ELEMENT seccion (titulo, parrafo*)>

<!ATTLIST proyecto lang (es | en | fr | ge) #REQUIRED>
<!ATTLIST apartado id ID #REQUIRED>
<!ATTLIST parrafo estilo (cita | codigo | normal) "normal">

=== rpf1980/Desarrollo-Web/Ejercicios tipo examen XML DTD, CSS y XSLT/examen-01-proyecto - copia/alumnos/e1-atributos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE proyecto
  SYSTEM 'e1-atributos.dtd'>
<proyecto lang="es">
  <datos_proyecto>
    <titulo>LMSGI</titulo>
    <autor>
      <nombre>Dexter</nombre>
      <apellidos>Morgan</apellidos>
    </autor>
    <autor>
      <nombre>Linus</nombre>
      <apellidos>Torvalds</apellidos>
    </autor>
  </datos_proyecto>
  <dedicatoria>
    <parrafo>A nuestros queridos alumnos</parrafo>
  </dedicatoria>
  <apartado id="Apart_01">
    <titulo>Introducción  a  la  administración de Linux</titulo>
    <seccion>
      <titulo>Objetivo de la práctica </titulo>
      <parrafo>El objetivo fundamental de esta práctica es que sefamiliarice con las diferentes interfaces
gráficas y de texto que posee Linux Debian. Concretamente se centrará la atención en las interfaces
GNOME y KDE así como en el uso del shell Bash (Bourne again shell). 
      </parrafo>
      <parrafo>Además se proporcionarán las nociones necesarias para la administración básica del 
sistema operativo.</parrafo>
    </seccion>
  </apartado>
  <apartado id="Apart_02">
    <titulo>Administración en red del S.O. Linux</titulo>
    <seccion>
      <titulo>Introducción</titulo>
      <parrafo estilo="cita">En una red de área local (LAN) los equipos están configurados de forma que sea posible la comunicación entre los mismos, el acceso  a  otros equipos  que proporcionan  servicios y el acceso al exterior de dicha red en el caso de que sea necesario  solicitar  servicios  que  no  proporcionan los servidores locales.</parrafo>
      <parrafo/>
    </seccion>
    <seccion>
      <titulo>Objetivo de la práctica</titulo>
      <parrafo>El objetivo de esta práctica es descubrir la configuración de la red  en la que está operando su equipo. Elalumno deberá  descubrir  la configuración IP de éste (dirección física, dirección IP, máscara 
de red, servidores, etc.), así como la de otros. </parrafo>
      <parrafo estilo="codigo">El segundo objetivo de  esta práctica es que  el  alumno se  familiarice con el  uso de las herramientas de  monitorización que  existen para redes en las que todos  los  equipos comparten un medio común. El uso de un medio  común, como sucede con las redes Ethernet, puede generar problemas bajo de terminadas condiciones,  los  cuales  pueden prevenirse o detectarse  con la utilización de las he rramientas aquí estudiadas.
      </parrafo>
    </seccion>
  </apartado>
  <apartado id="Apart_03">
    <titulo>Programación Shell-script en Linux</titulo>
  </apartado>
  <apartado id="Apart_04">
    <titulo>Introducción a la Programación Web</titulo>
    <seccion>
      <titulo>Despliegue de aplicaciones web </titulo>
    </seccion>
  </apartado>
</proyecto>
